#!/usr/bin/env python3
"""Bundles the site into ONE self-contained HTML file (artifact.html).

The markup is EXTRACTED from index.html and quiz.html rather than duplicated
here -- an earlier version kept its own copy of the hub, which silently drifted
out of sync. Edit the real pages; this just inlines them.

Dependency-free. Run:  python3 build_quiz_data.py && python3 build_artifact.py
"""

import json
import re
import sys
from pathlib import Path

SITE = Path(__file__).parent
OUT = SITE / "artifact.html"

# The artifact wrapper owns <head>, so this file can't declare a charset. A
# browser that guesses windows-1252 would render every dash and emoji as
# mojibake -- so the output is kept pure ASCII and is charset-proof.
ASCII_MAP = {
    "—": "&mdash;", "–": "&ndash;", "‘": "&lsquo;", "’": "&rsquo;",
    "“": "&ldquo;", "”": "&rdquo;", "·": "&middot;", "→": "&rarr;",
    "←": "&larr;", "…": "&hellip;", "×": "&times;", "⚠": "!",
}
CSS_MAP = {"—": "--", "–": "-", "’": "'", "·": "-", "→": "->", "⚠": "!"}


def html_ascii(text):
    for bad, good in ASCII_MAP.items():
        text = text.replace(bad, good)
    return text


def css_ascii(text):
    """CSS comments only -- entities would not be decoded inside <style>."""
    for bad, good in CSS_MAP.items():
        text = text.replace(bad, good)
    return text


def js_ascii(text):
    r"""JS strings the user actually sees -- \uXXXX keeps the real character
    instead of flattening an em dash to '--'."""
    return "".join(c if ord(c) < 128 else "\\u%04x" % ord(c) for c in text)


def body_of(path):
    """Everything inside <body>, minus the script tags the bundle re-adds."""
    src = path.read_text(encoding="utf-8")
    m = re.search(r"<body[^>]*>(.*)</body>", src, re.S | re.I)
    if not m:
        raise SystemExit(f"{path.name}: no <body> found")
    body = m.group(1)
    body = re.sub(r"<script\b.*?</script>", "", body, flags=re.S | re.I)
    return html_ascii(body.strip())


def main():
    css = css_ascii((SITE / "style.css").read_text(encoding="utf-8"))
    js = js_ascii((SITE / "app.js").read_text(encoding="utf-8"))
    data = json.loads((SITE / "quizzes.json").read_text(encoding="utf-8"))

    hub = body_of(SITE / "quizzes.html")
    runner = body_of(SITE / "quiz.html")

    # ensure_ascii escapes every non-ASCII character (emoji included) to \uXXXX,
    # which JavaScript decodes no matter what charset the page loads as.
    # </script> inside the JSON would close the tag early.
    payload = json.dumps(data, ensure_ascii=True).replace("</", "<\\/")

    html = f"""<!-- generated by build_artifact.py - edit quizzes.html / quiz.html / style.css / app.js -->
<title>Career Canvas &mdash; Find your path</title>
<style>
{css}
/* single-file build: hub and quiz share one page, routed by #hash */
[hidden] {{ display: none !important; }}
</style>

{runner}

{hub}

<script>window.__QUIZ_DATA__ = {payload};</script>
<script>
document.body.dataset.page = "single";
/* hide the quiz shell until the router decides, so it doesn't flash */
document.getElementById("topbar").hidden = true;
document.getElementById("runner").hidden = true;
{js}
</script>
"""

    OUT.write_text(html, encoding="utf-8")

    problems = []
    try:
        html.encode("ascii")
    except UnicodeEncodeError as e:
        problems.append(f"non-ASCII {html[e.start]!r} at {e.start} - would mojibake")
    # The artifact CSP blocks *subresource* loads to other hosts (scripts,
    # styles, images, fetch) -- it does not block a plain <a href> navigation,
    # so DECA event links (deca.org) are fine. GROUP_ENDPOINT/TALLY_ENDPOINT
    # stay "" by default; if Jada ever pastes a live URL into either, that
    # constant becomes a runtime fetch/script-src target the CSP WILL block,
    # which is a decision for her to make deliberately, not something this
    # build script can validate for.
    if re.search(r'src="https?://', html) or re.search(r"url\(https?://", html):
        problems.append("external subresource (src=/url()) - the artifact CSP blocks other hosts")
    for tag in ("<!doctype", "<html", "<head>", "<body"):
        if tag in html.lower():
            problems.append(f"contains {tag} - the artifact wrapper supplies it")
    for need in ('id="hub"', 'id="runner"', 'id="topbar"', 'id="cards"', 'id="main"'):
        if need not in html:
            problems.append(f"missing {need} - extraction from the source pages failed")

    if problems:
        print("FAIL:")
        for p in problems:
            print(f"  X {p}")
        return 1

    print(f"PASS: wrote {OUT.name} ({OUT.stat().st_size // 1024} KB), "
          f"markup extracted from quizzes.html + quiz.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
